//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keynvaders.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keynvaders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}. {1} &gt;&gt; {2}.
        /// </summary>
        internal static string HIGHSCORE_DISPLAY {
            get {
                return ResourceManager.GetString("HIGHSCORE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No high scores!.
        /// </summary>
        internal static string HIGHSCORE_NOSCORES {
            get {
                return ResourceManager.GetString("HIGHSCORE_NOSCORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lbGame.
        /// </summary>
        internal static string LBGAME {
            get {
                return ResourceManager.GetString("LBGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lbQck.
        /// </summary>
        internal static string LBGAME_QCK {
            get {
                return ResourceManager.GetString("LBGAME_QCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pauseLabel.
        /// </summary>
        internal static string LBPAUSE {
            get {
                return ResourceManager.GetString("LBPAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAME PAUSED.
        /// </summary>
        internal static string LBPAUSE_TXT {
            get {
                return ResourceManager.GetString("LBPAUSE_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oh no!.
        /// </summary>
        internal static string MSG_ERRORSAVE_TITLE {
            get {
                return ResourceManager.GetString("MSG_ERRORSAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving the high score.
        /// </summary>
        internal static string MSG_ERRORSAVE_TXT {
            get {
                return ResourceManager.GetString("MSG_ERRORSAVE_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You lost!.
        /// </summary>
        internal static string MSG_LOSE_TITLE {
            get {
                return ResourceManager.GetString("MSG_LOSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your score was {0}.
        /// </summary>
        internal static string MSG_LOSE_TXT {
            get {
                return ResourceManager.GetString("MSG_LOSE_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Level = .
        /// </summary>
        internal static string TITLE_LEVEL {
            get {
                return ResourceManager.GetString("TITLE_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KeyNvaders.
        /// </summary>
        internal static string TITLE_MAIN {
            get {
                return ResourceManager.GetString("TITLE_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Score = .
        /// </summary>
        internal static string TITLE_SCORE {
            get {
                return ResourceManager.GetString("TITLE_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abcdefghijklmnñopqrstuvwxyz.
        /// </summary>
        internal static string VALID_CHARS {
            get {
                return ResourceManager.GetString("VALID_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon Vcferreira_Firefox_Os_Keyboard {
            get {
                object obj = ResourceManager.GetObject("Vcferreira_Firefox_Os_Keyboard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
